Settings:
  task-interval: 30
  update-interval: 600
  price-per-repair: 10
Messages:
  actionbar: '&6&lVoltz&f&lMC &8&l➜ &7Você quebrou &f{blocks} &7blocos e recebeu:
    &e{coins}✪ &7e &5{tokens}✦&7!'
  mining-usage: '&6&lVoltz&f&lMC &8&l➜ &cUso correto: /miningadmin <setupgrade/settrade/reload>.'
  booster-usage: '&6&lVoltz&f&lMC &8&l➜ &cUso correto: /miningbooster give <jogador> <tipo> <multiplier> <duração> <quantia>.'
  config-reloaded: '&6&lVoltz&f&lMC &8&l➜ &aConfiguração recarregada com sucesso!'
  location-set: '&6&lVoltz&f&lMC &8&l➜ &aLocal definido com sucesso!'
  upgrade-type: '&6&lVoltz&f&lMC &8&l➜ &aDigite no chat a quantia de níveis que deseja
    evoluir!'
  upgrade-cancelled: '&6&lVoltz&f&lMC &8&l➜ &cEvolução cancelada!'
  upgrade-maximum-level: '&6&lVoltz&f&lMC &8&l➜ &cO nível ultrapassou o limite! Tente
    novamente com um valor menor.'
  insufficient-tokens: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui Tokens suficientes!'
  offline-player: '&6&lVoltz&f&lMC &8&l➜ &cEsse jogador está offline!'
  invalid-value: '&6&lVoltz&f&lMC &8&l➜ &cValor inválido!'
  invalid-booster: '&6&lVoltz&f&lMC &8&l➜ &cBooster inválido! Tipos válidos: REWARDS, TREASURES e BLOCKS!'
  has-booster-actived: '&6&lVoltz&f&lMC &8&l➜ &cVocê já possui um booster desse tipo ativo!'
  booster-ended: '&6&lVoltz&f&lMC &8&l➜ &cO seu booster de {type} acabou!'
  tokens:
    message: '&6&lVoltz&f&lMC &8&l➜ &7Você possui: &5{tokens}✦&7!'
    title: '&5&lTokens'
    subtitle: '&fVocê possui: &5{tokens}✦&f!'
Pickaxe:
  type: DIAMOND_PICKAXE
  attributes: false
  name: '&8&lPicareta Dark &7[Lvl: &f{level}&7]'
  lore:
    - '&7Eficiência: &f{dig_speed}'
    - '&7Inquebrável: &f{durability}'
    - '&7Fortuna: &f{loot_bonus_blocks}'
    - '&7Super Área: &f{super_area}'
    - '&7Destruição: &f{destruction}'
    - '&7Sortudo: &f{lucky}'
    - '&7Thunder: &f{thunder}'
  enchants:
    - DIG_SPEED,{dig_speed}
    - DURABILITY,{durability}
Tokens:
  type: SKULL_ITEM
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWQ5MmZlZWExZGVlZTYxY2Q1ZTIzOWNiM2VkOWM0NDRlNTk3YzkxODMzMjZkMWZlODRiOTUyYzg1ZmVhMzNhIn19fQ==
  name: '&5Tokens &7[&fx{amount}&7]'
  lore:
    - '&7Ative esse item para ganhar'
    - '&7tokens e evoluir sua picareta!'
    - ''
    - '&7Para ativar todos Tokens de uma'
    - '&7só vez, basta segurar &fSHIFT!'
Booster:
  type: EXP_BOTTLE
  name: "&6Booster de {type}"
  lore:
    - '&7Duração: &f{duration} minutos'
    - '&7Multiplier: &f{multiplier}x'
BlocksItem:
  type: SKULL_ITEM
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjJmODAzNjMyNDRhZjFiNGJjZjdkMWMyYjUwNjc3NzJjMGMyNzI3NzI2NjQ0N2VjY2Q0YWY2NmNjNDM0NzM5OCJ9fX0=
  name: '&eBlocos &7[&f{amount}&7]'
  lore:
    - '&7Ative esse item para ganhar'
    - '&7blocos e trocar por itens raros!'
    - ''
    - '&7Para ativar todos Blocos de uma'
    - '&7só vez, basta segurar &fSHIFT!'
UpgradersItem:
  1:
    type: SKULL_ITEM
    owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjZhZDNmMzQzYmU4YzgwZTA0NzA1OThkMWVkMjdiZWI5MDg1ODM5NTczOTU1ZWQ5ZDQ2MjY4MDljMzgzYjFiNyJ9fX0=
    name: "&8Evoluir Picareta &7[&f+{upgrade}&7]"
    lore:
      - '&7Aplique esse item na sua picareta'
      - '&7para aumentar todos encantamentos'
      - '&7em &f{upgrade} &7níveis!'
    upgrade: 5
  2:
    type: SKULL_ITEM
    owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWJjNDhiYmQzOTJjYzkzMzhjZTU4MjQ5ZGU3NmU3Njk3OWFlZjdmZGExMGJkYzE3ZWMxYjY0NGZkYWM4MGMzMiJ9fX0=
    name: "&6Evoluir Picareta &7[&f+{upgrade}&7]"
    lore:
      - '&7Aplique esse item na sua picareta'
      - '&7para aumentar todos encantamentos'
      - '&7em &f{upgrade} &7níveis!'
    upgrade: 20
Regions:
  enter:
    - mina
  mine:
    - minerios
    - mineriosvip
    - mineriospvp
  blacklist:
    - mineriospvp
Blocks:
  NETHERRACK:
    coins: 7500
    tokens: 75
    lucky-block: false
  NETHER_BRICK:
    coins: 500000
    tokens: 5000
    lucky-block: false
  QUARTZ_ORE:
    coins: 10000
    tokens: 100
    lucky-block: true
Inventories:
  trade:
    title: Trocar Blocos
    size: 54
    items:
      info:
        type: SKULL_ITEM
        owner: '{player}'
        name: '&aEstatísticas'
        lore:
          - '&7Blocos quebrados: &f{broken}'
          - '&7Saldo de blocos: &f{avaible}'
        slot: 4
      close:
        type: ARROW
        name: '&cFechar'
        slot: 49
        action: CLOSE
      1:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjZhZDNmMzQzYmU4YzgwZTA0NzA1OThkMWVkMjdiZWI5MDg1ODM5NTczOTU1ZWQ5ZDQ2MjY4MDljMzgzYjFiNyJ9fX0=
        name: "&8Evoluir Picareta &7[&f+5&7]"
        lore:
          - '&7Aplique esse item na sua picareta'
          - '&7para aumentar todos encantamentos'
          - '&7em &f5 &7níveis!'
          - ""
          - '&7Custo: &f{price} blocos'
        price: 5000000
        slot: 20
        action: BUY
        commands:
          - 'upgrader {player} 1 1'
      2:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWJjNDhiYmQzOTJjYzkzMzhjZTU4MjQ5ZGU3NmU3Njk3OWFlZjdmZGExMGJkYzE3ZWMxYjY0NGZkYWM4MGMzMiJ9fX0=
        name: "&6Evoluir Picareta &7[&f+20&7]"
        lore:
          - '&7Aplique esse item na sua picareta'
          - '&7para aumentar todos encantamentos'
          - '&7em &f20 &7níveis!'
          - ''
          - '&7Custo: &f{price} blocos &7(-25%)'
        price: 15000000
        slot: 21
        action: BUY
        commands:
          - 'upgrader {player} 2 1'
      3:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjViNWZhYThlNDgxZmNiODRjYmVmMWU1YzQyMGQ2YTgxYTZlNjhmNWEwNzUwMDFhMDI4ODI1YWMyMDE4ZWJlNyJ9fX0=
        name: "&aEvoluir Looting &7[&f+1.000&7]"
        lore:
          - '&7Aplique esse item na sua looting'
          - '&7para aumentar todos encantamentos'
          - '&7em &f1.000 &7níveis!'
          - ''
          - '&7Esse adicional só pode ser aplicado'
          - '&7uma vez por item!'
          - ''
          - '&7Custo: &f{price} blocos'
        price: 500000000
        slot: 22
        action: BUY
        commands:
          - 'upgrader {player} 3 1'
      4:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjViNWZhYThlNDgxZmNiODRjYmVmMWU1YzQyMGQ2YTgxYTZlNjhmNWEwNzUwMDFhMDI4ODI1YWMyMDE4ZWJlNyJ9fX0=
        name: "&aEvoluir Looting &7[&f+1.500&7]"
        lore:
          - '&7Aplique esse item na sua looting'
          - '&7para aumentar todos encantamentos'
          - '&7em &f1.500 &7níveis!'
          - ''
          - '&7Esse adicional só pode ser aplicado'
          - '&7uma vez por item!'
          - ''
          - '&7Custo: &f{price} blocos'
        price: 750000000
        slot: 23
        action: BUY
        commands:
          - 'upgrader {player} 4 1'
      5:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWQ5MmZlZWExZGVlZTYxY2Q1ZTIzOWNiM2VkOWM0NDRlNTk3YzkxODMzMjZkMWZlODRiOTUyYzg1ZmVhMzNhIn19fQ==
        name: '&5Tokens &7[&fx100k&7]'
        lore:
          - '&7Ative esse item para ganhar'
          - '&7tokens e evoluir sua picareta!'
          - ''
          - '&7Para ativar todos Tokens de uma'
          - '&7só vez, basta segurar &fSHIFT!'
          - ''
          - '&7Custo: &f{price} blocos'
        price: 100000
        slot: 24
        action: BUY
        commands:
          - 'tokens vale {player} 100000'
      6:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWQ5MmZlZWExZGVlZTYxY2Q1ZTIzOWNiM2VkOWM0NDRlNTk3YzkxODMzMjZkMWZlODRiOTUyYzg1ZmVhMzNhIn19fQ==
        name: '&5Tokens &7[&fx100k&7]'
        lore:
          - '&7Ative esse item para ganhar'
          - '&7tokens e evoluir sua picareta!'
          - ''
          - '&7Para ativar todos Tokens de uma'
          - '&7só vez, basta segurar &fSHIFT!'
          - ''
          - '&7Custo: &f{price} blocos'
        price: 1000000
        slot: 24
        action: BUY
        commands:
          - 'tokens vale {player} 100000'
      7:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWQ5MmZlZWExZGVlZTYxY2Q1ZTIzOWNiM2VkOWM0NDRlNTk3YzkxODMzMjZkMWZlODRiOTUyYzg1ZmVhMzNhIn19fQ==
        name: '&5Tokens &7[&fx500k&7]'
        lore:
          - '&7Ative esse item para ganhar'
          - '&7tokens e evoluir sua picareta!'
          - ''
          - '&7Para ativar todos Tokens de uma'
          - '&7só vez, basta segurar &fSHIFT!'
          - ''
          - '&7Custo: &f{price} blocos &7(-25%)'
        price: 3750000
        slot: 30
        action: BUY
        commands:
          - 'tokens vale {player} 500000'
      8:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODkzNzVkODA1MjkxYmFjN2QwNDVjNWMwNDQ4YWI3ZjU1OTlmYTZkOWE4Y2FlYWU0YmQyNTFkNTg2ZTJjOCJ9fX0=
        name: '&bEvoluir Armadura &7[&f+2&7]'
        lore:
          - '&7Aplique esse item na sua armadura'
          - '&7para aumentar todos encantamentos'
          - '&7em &f2 &7níveis!'
          - ''
          - '&7Esse adicional só pode ser aplicado'
          - '&7uma vez por item!'
          - ''
          - '&7Custo: &f{price} blocos'
        price: 10000000
        slot: 31
        action: BUY
        commands:
          - 'upgradearmor {player} 1 1'
      9:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWJmYTZlYWI4MWUyMWJkYmZiYjk4N2VkNjk1YTQ1OTZlZDMzZTc3NTEwOTA4ZGFkZjY5NjkxMmY5NDIzZjc1In19fQ==
        name: '&4Evoluir Armadura &7[&f+3&7]'
        lore:
          - '&7Aplique esse item na sua armadura'
          - '&7para aumentar todos encantamentos'
          - '&7em &f3 &7níveis!'
          - ''
          - '&7Esse adicional só pode ser aplicado'
          - '&7uma vez por item!'
          - ''
          - '&7Custo: &f{price} blocos'
        price: 15000000
        slot: 32
        action: BUY
        commands:
          - 'upgradearmor {player} 2 1'
  upgrade:
    title: Evoluir Picareta
    size: 54
    items:
      pickaxe:
        slot: 3
      top:
        type: ARMOR_STAND
        name: '&aTop 10'
        lore:
          - '&7Clique para ver os &f10 jogadores'
          - '&7que mais quebraram blocos no servidor!'
        slot: 5
        action: TOP
      close:
        type: ARROW
        name: '&cFechar'
        slot: 49
        action: CLOSE
      dig_speed:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTJjZTRkYjNlODQ3MmJjNDkxNDI1N2U5ZjJkMWM1YjE1MTcyZWE2NzUyYmI5N2Q5YjRlOWExMDMyNGFhMjg2In19fQ==
        name: '&aEficiência &7[Máx: &f{max_level}&7]'
        lore:
          - '&fAo evoluir esse encantamento, sua picareta'
          - '&fse tornará mais eficiente!'
          - ''
          - '&7Nível atual: &f{level}'
          - '&7Custo para evoluir: &f{price} Tokens'
          - ''
          - '&7Clique para escolher os níveis!'
        slot: 21
        action: UPGRADE
      durability:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmJiZTQxYmYyM2MzY2RmZTNkZGVkNDIyZjQ4NDQ1MzExNDgxM2UxMmY3YjZmODU1OTM1NTJhNTVjMDgwM2MifX19
        name: '&aInquebrável &7[Máx: &f{max_level}&7]'
        lore:
          - '&fAo evoluir esse encantamento, sua picareta'
          - '&fse tornará mais resistente!'
          - ''
          - '&7Nível atual: &f{level}'
          - '&7Custo para evoluir: &f{price} Tokens'
          - ''
          - '&7Clique para escolher os níveis!'
        slot: 22
        action: UPGRADE
      loot_bonus_blocks:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTFmZjZhNTVlOTcxOTMxZWIwNjI2NTY1ZGFkNzc3MTQxOWZhZTk4ODdhYTZkNTJiZjE5OTU3MTc4NjBjIn19fQ==
        name: '&aFortuna &7[Máx: &f{max_level}&7]'
        lore:
          - '&fAo evoluir esse encantamento, sua picareta'
          - '&ffornecerá mais coins e tokens!'
          - ''
          - '&7Nível atual: &f{level}'
          - '&7Custo para evoluir: &f{price} Tokens'
          - ''
          - '&7Clique para escolher os níveis!'
        slot: 23
        action: UPGRADE
      super_area:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTMzYTQyNWUyZjhiYmM1MDk5ZjAxNDJmM2RjMTRiNWI0MGVkMmRkMzY2YWNlNjhiZjlmNzE4NjM0NGJkMjMzMSJ9fX0=
        name: '&aSuper Área &7[Máx: &f{max_level}&7]'
        lore:
          - '&fAo evoluir esse encantamento, sua picareta'
          - '&fterá uma chance de quebrar em área!'
          - ''
          - '&7Nível atual: &f{level}'
          - '&7Custo para evoluir: &f{price} Tokens'
          - ''
          - '&7Clique para escolher os níveis!'
        slot: 30
        action: UPGRADE
      destruction:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWM1YTYyZWRlNTIwYzQ4ZGI0OTkzNTQzZWUyZjFiYjQ2N2E3YTNmMDE5MGI2ZWNmYjI3MDViMDBjNGJiMThjMyJ9fX0=
        name: '&aDestruição &7[Máx: &f{max_level}&7]'
        lore:
          - '&fAo evoluir esse encantamento, sua picareta'
          - '&fterá uma chance de quebrar uma camada inteira!'
          - ''
          - '&7Nível atual: &f{level}'
          - '&7Custo para evoluir: &f{price} Tokens'
          - ''
          - '&7Clique para escolher os níveis!'
        slot: 31
        action: UPGRADE
      lucky:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGY3NDY3YzVmNzM4YzY0MTI0NmMwOWY4Y2U3OTFlMzM5YTg2ZTgxZGU2MjA0OWI0MWY0OTI4ODgxNzJmYTcyNiJ9fX0=
        name: '&aSortudo &7[Máx: &f{max_level}&7]'
        lore:
          - '&fAo evoluir esse encantamento, sua picareta'
          - '&fterá uma chance maior de encontrar tesouros!'
          - ''
          - '&7Nível atual: &f{level}'
          - '&7Custo para evoluir: &f{price} Tokens'
          - ''
          - '&7Clique para escolher os níveis!'
        slot: 32
        action: UPGRADE
      thunder:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDgwNjhhM2U5ZWQwZTY4ODc2OGNmZTAxN2VhZGZmZmM5MjEwNjhmYjRhOGExMGJhYmFkY2U3NWNmNTcyYWFhMyJ9fX0=
        name: '&aThunder &7[Máx: &f{max_level}&7]'
        lore:
          - '&fAo evoluir esse encantamento, sua picareta'
          - '&fterá uma chance de invocar um raio, quebrando'
          - '&ftodos blocos até a última camada!'
          - ''
          - '&7Nível atual: &f{level}'
          - '&7Custo para evoluir: &f{price} Tokens'
          - ''
          - '&7Clique para escolher os níveis!'
        slot: 39
        action: UPGRADE
  repair:
    title: Reparar Picareta
    size: 45
    items:
      pickaxe:
        slot: 13
      repair:
        type: SKULL_ITEM
        owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWI0MjVhYTNkOTQ2MThhODdkYWM5Yzk0ZjM3N2FmNmNhNDk4NGMwNzU3OTY3NGZhZDkxN2Y2MDJiN2JmMjM1In19fQ==
        name: '&aReparar'
        lore:
          - '&7Porcentagem danificada: &f{percentage}%'
          - ''
          - '&7Custo: &f{price} Tokens'
          - ''
          - '&7Clique para reparar!'
        slot: 31
        action: REPAIR
  top:
    title: Mineração - Top 10
    size: 36
    slots: 11,12,13,14,15,20,21,22,23,24
    items:
      player:
        type: SKULL_ITEM
        owner: '{player}'
        name: '&5{player} &7[&f{pos}º&7]'
        lore:
          - '&7Blocos quebrados: &f{broken}'
          - '&7Saldo de Blocos: &f{avaible}'
      back:
        type: ARROW
        name: '&cVoltar'
        slot: 27
        action: MAIN
Enchants:
  DIG_SPEED:
    max-level: 1000
    price-per-level: 7500
    initial-level: 10
  DURABILITY:
    max-level: 1000
    price-per-level: 5000
    initial-level: 0
  LOOT_BONUS_BLOCKS:
    max-level: 1000
    price-per-level: 7500
    initial-level: 0
  SUPER_AREA:
    max-level: 100
    price-per-level: 12500
    initial-level: 0
  DESTRUCTION:
    max-level: 100
    price-per-level: 25000
    initial-level: 0
  LUCKY:
    max-level: 100
    price-per-level: 10000
    initial-level: 0
  THUNDER:
    max-level: 100
    price-per-level: 20000
    initial-level: 0
Treasures:
  '1':
    chance: 1
    commands:
      - darkit Belzebu {player}
    title: '&8&lTesouros'
    subtitle: '&f+1 Chave Belzebu'
  '2':
    chance: 0.5
    commands:
      - tokens vale {player} 500
    title: '&8&lTesouros'
    subtitle: '&f+500 Tokens'
  '3':
    chance: 0.3
    commands:
      - rank givefragmentos {player} 25000
    title: '&8&lTesouros'
    subtitle: '&f+25.000 fragmentos'
  '4':
    chance: 0.2
    commands:
      - rank givefragmentos {player} 50000
    title: '&8&lTesouros'
    subtitle: '&f+50.000 fragmentos'
  '5':
    chance: 0.1
    commands:
      - rank givefragmentos {player} 75000
    title: '&8&lTesouros'
    subtitle: '&f+75.000 fragmentos'
  '6':
    chance: 0.05
    commands:
      - amc sgive {player} Lucky 1
    title: '&8&lTesouros'
    subtitle: '&f+1 Lucky Block'
Upgrade-Location: RankupWorld#1007#51#1012
Trade-Location: RankupWorld#1007#51#1006